FROM salesforce/salesforcedx:latest-full

ENV HOME=/tmp

RUN sfdx update \
  && echo y | sfdx plugins:install sfdmu \
  && echo y | sfdx plugins:install shane-sfdx-plugins \
  && echo y | sfdx plugins:install @dx-cli-toolbox/sfdx-toolbox-package-utils \
  && echo y | sfdx plugins:install sfpowerkit

RUN rm $HOME/.sfdx/sfdx.log
RUN chmod -R 666 $HOME/.sfdx

chmod -R a+rw 